pipeline:
  identifier: Build_harness_ci_example_1689751797786
  name: Build harness-ci-example
  orgIdentifier: default
  projectIdentifier: ecrpushpr
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: yaduchannakeshava/harness-ci-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: vijayacon
                    region: ap-south-1
                    account: "506379294322"
                    imageName: harness-yadu
                    tags:
                      - test-repo
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
