pipeline:
  identifier: Build_harness_ci_example_1689751797786
  name: Build harness-ci-example
  orgIdentifier: default
  projectIdentifier: ecrpushpr
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: yaduchannakeshava/harness-ci-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    shell: Sh
                    command: |-
                      FROM komljen/ubuntu
                      MAINTAINER Alen Komljen <alen.komljen@live.com>

                      RUN \
                        apt-get update && \
                        apt-get -y install \
                                apache2 && \
                        rm /var/www/html/index.html && \
                        rm -rf /var/lib/apt/lists/*
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: vijayacon
                    region: ap-south-1
                    account: "506379294322"
                    imageName: ci-nodejs
                    tags:
                      - testing
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
